# Análisis del dataset SWELL

In [1]:
# Importamos los módulos
import pandas as pd
import numpy as np

In [2]:
# Leemos los valores de test y entrenamiento
test = pd.read_csv('SWELL_test.csv')
train = pd.read_csv('SWELL_train.csv')

In [3]:
# Dimensiones de los datasets
print(test.shape)
print(train.shape)

(41033, 36)
(369289, 36)

In [4]:
train.head()

,MEAN_RR,MEDIAN_RR,SDRR,RMSSD,SDSD,SDRR_RMSSD,HR,pNN25,pNN50,SD1,...,HF,HF_PCT,HF_NU,TP,LF_HF,HF_LF,sampen,higuci,datasetId,condition
0,885.157845,853.763730,140.972741,15.554505,15.553371,9.063146,69.499952,11.133333,0.533333,11.001565,...,15.522603,0.421047,1.514737,3686.666157,65.018055,0.015380,2.139754,1.163485,2,no stress
1,939.425371,948.357865,81.317742,12.964439,12.964195,6.272369,64.363150,5.600000,0.000000,9.170129,...,2.108525,0.070133,0.304603,3006.487251,327.296635,0.003055,2.174499,1.084711,2,interruption
2,898.186047,907.006860,84.497236,16.305279,16.305274,5.182201,67.450066,13.066667,0.200000,11.533417,...,13.769729,0.512671,1.049528,2685.879461,94.280910,0.010607,2.135350,1.176315,2,interruption
3,881.757865,893.460030,90.370537,15.720468,15.720068,5.748591,68.809562,11.800000,0.133333,11.119476,...,18.181913,0.529387,1.775294,3434.520980,55.328701,0.018074,2.178341,1.179688,2,no stress
4,809.625331,811.184865,62.766242,19.213819,19.213657,3.266724,74.565728,20.200000,0.200000,13.590641,...,48.215822,1.839473,3.279993,2621.175204,29.487873,0.033912,2.221121,1.249612,2,no stress

In [5]:
train.dtypes

MEAN_RR              float64
MEDIAN_RR            float64
SDRR                 float64
RMSSD                float64
SDSD                 float64
SDRR_RMSSD           float64
HR                   float64
pNN25                float64
pNN50                float64
SD1                  float64
SD2                  float64
KURT                 float64
SKEW                 float64
MEAN_REL_RR          float64
MEDIAN_REL_RR        float64
SDRR_REL_RR          float64
RMSSD_REL_RR         float64
SDSD_REL_RR          float64
SDRR_RMSSD_REL_RR    float64
KURT_REL_RR          float64
SKEW_REL_RR          float64
VLF                  float64
VLF_PCT              float64
LF                   float64
LF_PCT               float64
LF_NU                float64
HF                   float64
HF_PCT               float64
HF_NU                float64
TP                   float64
LF_HF                float64
HF_LF                float64
sampen               float64
higuci               float64
datasetId              int64
condition             object
dtype: object

In [6]:
train.describe()

,MEAN_RR,MEDIAN_RR,SDRR,RMSSD,SDSD,SDRR_RMSSD,HR,pNN25,pNN50,SD1,...,LF_NU,HF,HF_PCT,HF_NU,TP,LF_HF,HF_LF,sampen,higuci,datasetId
count,369289.000000,369289.000000,369289.000000,369289.000000,369289.000000,369289.000000,369289.000000,369289.000000,369289.000000,369289.000000,...,369289.000000,369289.000000,369289.000000,369289.000000,369289.000000,369289.000000,369289.000000,369289.000000,369289.000000,369289.0
mean,846.650104,841.965890,109.352531,14.977498,14.976767,7.396597,73.941824,9.841143,0.866001,10.593708,...,95.566718,39.245603,1.615576,4.433282,3185.356025,115.977200,0.048506,2.062471,1.182292,2.0
std,124.603984,132.321005,77.117025,4.120766,4.120768,5.143834,10.337453,8.195574,0.990189,2.914795,...,4.123365,45.398869,1.761073,4.123365,1923.227187,360.855129,0.049238,0.206999,0.062192,0.0
min,547.492221,517.293295,27.233947,5.529742,5.529630,2.660381,48.737243,0.000000,0.000000,3.911344,...,69.879083,0.061783,0.002150,0.012825,377.692795,2.319952,0.000128,0.434576,1.033984,2.0
25%,760.228533,755.750735,64.205641,11.830959,11.830671,4.541896,66.715776,3.666667,0.000000,8.368340,...,93.645734,10.720312,0.346803,1.228054,1828.147788,14.737458,0.012433,2.032977,1.139929,2.0
50%,822.951438,819.689595,82.608243,14.415918,14.415388,5.952112,74.217809,7.600000,0.466667,10.196621,...,96.643140,24.841938,1.039513,3.356860,2796.856587,28.789747,0.034735,2.134214,1.174293,2.0
75%,924.117422,916.821570,118.237002,17.927144,17.924839,7.919841,80.334937,13.333333,1.466667,12.679005,...,98.771946,45.272368,2.245115,6.354266,4052.260157,80.429614,0.067854,2.181929,1.223621,2.0
max,1322.016957,1653.122250,563.486949,26.629477,26.629392,54.523950,113.752309,39.400000,5.466667,18.836107,...,99.987175,364.486936,13.095664,30.120917,13390.684098,7796.443096,0.431043,2.234841,1.361219,2.0

In [7]:
train.describe(include = "all")

,MEAN_RR,MEDIAN_RR,SDRR,RMSSD,SDSD,SDRR_RMSSD,HR,pNN25,pNN50,SD1,...,HF,HF_PCT,HF_NU,TP,LF_HF,HF_LF,sampen,higuci,datasetId,condition
count,369289.000000,369289.000000,369289.000000,369289.000000,369289.000000,369289.000000,369289.000000,369289.000000,369289.000000,369289.000000,...,369289.000000,369289.000000,369289.000000,369289.000000,369289.000000,369289.000000,369289.000000,369289.000000,369289.0,369289
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,no stress
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,200082
mean,846.650104,841.965890,109.352531,14.977498,14.976767,7.396597,73.941824,9.841143,0.866001,10.593708,...,39.245603,1.615576,4.433282,3185.356025,115.977200,0.048506,2.062471,1.182292,2.0,NaN
std,124.603984,132.321005,77.117025,4.120766,4.120768,5.143834,10.337453,8.195574,0.990189,2.914795,...,45.398869,1.761073,4.123365,1923.227187,360.855129,0.049238,0.206999,0.062192,0.0,NaN
min,547.492221,517.293295,27.233947,5.529742,5.529630,2.660381,48.737243,0.000000,0.000000,3.911344,...,0.061783,0.002150,0.012825,377.692795,2.319952,0.000128,0.434576,1.033984,2.0,NaN
25%,760.228533,755.750735,64.205641,11.830959,11.830671,4.541896,66.715776,3.666667,0.000000,8.368340,...,10.720312,0.346803,1.228054,1828.147788,14.737458,0.012433,2.032977,1.139929,2.0,NaN
50%,822.951438,819.689595,82.608243,14.415918,14.415388,5.952112,74.217809,7.600000,0.466667,10.196621,...,24.841938,1.039513,3.356860,2796.856587,28.789747,0.034735,2.134214,1.174293,2.0,NaN
75%,924.117422,916.821570,118.237002,17.927144,17.924839,7.919841,80.334937,13.333333,1.466667,12.679005,...,45.272368,2.245115,6.354266,4052.260157,80.429614,0.067854,2.181929,1.223621,2.0,NaN
max,1322.016957,1653.122250,563.486949,26.629477,26.629392,54.523950,113.752309,39.400000,5.466667,18.836107,...,364.486936,13.095664,30.120917,13390.684098,7796.443096,0.431043,2.234841,1.361219,2.0,NaN

In [8]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 369289 entries, 0 to 369288
Data columns (total 36 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   MEAN_RR            369289 non-null  float64
 1   MEDIAN_RR          369289 non-null  float64
 2   SDRR               369289 non-null  float64
 3   RMSSD              369289 non-null  float64
 4   SDSD               369289 non-null  float64
 5   SDRR_RMSSD         369289 non-null  float64
 6   HR                 369289 non-null  float64
 7   pNN25              369289 non-null  float64
 8   pNN50              369289 non-null  float64
 9   SD1                369289 non-null  float64
 10  SD2                369289 non-null  float64
 11  KURT               369289 non-null  float64
 12  SKEW               369289 non-null  float64
 13  MEAN_REL_RR        369289 non-null  float64
 14  MEDIAN_REL_RR      369289 non-null  float64
 15  SDRR_REL_RR        369289 non-null  float64
 16  RMSSD_REL_RR       369289 non-null  float64
 17  SDSD_REL_RR        369289 non-null  float64
 18  SDRR_RMSSD_REL_RR  369289 non-null  float64
 19  KURT_REL_RR        369289 non-null  float64
 20  SKEW_REL_RR        369289 non-null  float64
 21  VLF                369289 non-null  float64
 22  VLF_PCT            369289 non-null  float64
 23  LF                 369289 non-null  float64
 24  LF_PCT             369289 non-null  float64
 25  LF_NU              369289 non-null  float64
 26  HF                 369289 non-null  float64
 27  HF_PCT             369289 non-null  float64
 28  HF_NU              369289 non-null  float64
 29  TP                 369289 non-null  float64
 30  LF_HF              369289 non-null  float64
 31  HF_LF              369289 non-null  float64
 32  sampen             369289 non-null  float64
 33  higuci             369289 non-null  float64
 34  datasetId          369289 non-null  int64
 35  condition          369289 non-null  object
dtypes: float64(34), int64(1), object(1)
memory usage: 101.4+ MB

In [9]:
# Número de datos nulos
train.isnull().sum()

MEAN_RR              0
MEDIAN_RR            0
SDRR                 0
RMSSD                0
SDSD                 0
SDRR_RMSSD           0
HR                   0
pNN25                0
pNN50                0
SD1                  0
SD2                  0
KURT                 0
SKEW                 0
MEAN_REL_RR          0
MEDIAN_REL_RR        0
SDRR_REL_RR          0
RMSSD_REL_RR         0
SDSD_REL_RR          0
SDRR_RMSSD_REL_RR    0
KURT_REL_RR          0
SKEW_REL_RR          0
VLF                  0
VLF_PCT              0
LF                   0
LF_PCT               0
LF_NU                0
HF                   0
HF_PCT               0
HF_NU                0
TP                   0
LF_HF                0
HF_LF                0
sampen               0
higuci               0
datasetId            0
condition            0
dtype: int64

In [10]:
# Número de datos nulos
test.isnull().sum()

MEAN_RR              0
MEDIAN_RR            0
SDRR                 0
RMSSD                0
SDSD                 0
SDRR_RMSSD           0
HR                   0
pNN25                0
pNN50                0
SD1                  0
SD2                  0
KURT                 0
SKEW                 0
MEAN_REL_RR          0
MEDIAN_REL_RR        0
SDRR_REL_RR          0
RMSSD_REL_RR         0
SDSD_REL_RR          0
SDRR_RMSSD_REL_RR    0
KURT_REL_RR          0
SKEW_REL_RR          0
VLF                  0
VLF_PCT              0
LF                   0
LF_PCT               0
LF_NU                0
HF                   0
HF_PCT               0
HF_NU                0
TP                   0
LF_HF                0
HF_LF                0
sampen               0
higuci               0
datasetId            0
condition            0
dtype: int64

In [11]:
# Distribución de los datos de entrenamiento
train["condition"].value_counts(sort=False)

interruption     105150
no stress        200082
time pressure     64057
Name: condition, dtype: int64

In [12]:
# Distribución de los datos de test
test["condition"].value_counts(sort=False)

interruption     11782
no stress        22158
time pressure     7093
Name: condition, dtype: int64